### ISSUE TITLE
Problem on archlinux and go 1.18

### ISSUE THREAD

**Issue by mohad12211** [diamondburned/gotk4-examples#18]
using archlinux, go 1.18
when I run any example with `go run -v `
```
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.18 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.18 set. Notably, if go1.18 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
	/home/mohad/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20201222180813-1025295fd063/untested.go:24 +0x1f4
exit status 2
```
running it with ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.18 does seem to work, but it crashes in `cssdemo`
with:
```
2022/03/31 04:26:29 CSS error (Unterminated block at end of document) at line: "html {"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10000 pc=0x7fef3ecffc96]

runtime stack:
runtime.throw({0x935a42?, 0x28e7750?})
	/usr/lib/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x789c60, 0xc00014faa0)
	/usr/lib/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00014fa78 sp=0xc00014fa40 pc=0x54de9c
github.com/diamondburned/gotk4/pkg/gtk/v4._Cfunc_gtk_label_new(0x290df00)
	_cgo_gotypes.go:26215 +0x49 fp=0xc00014faa0 sp=0xc00014fa78 pc=0x6bc929
github.com/diamondburned/gotk4/pkg/gtk/v4.NewLabel({0x92a41b, 0x5})
	/home/mohad/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20220221063304-bbd86ac49f1b/gtk/v4/gtklabel.go:393 +0x70 fp=0xc00014fb00 sp=0xc00014faa0 pc=0x6fef50
main.activate(0x80?)
	/home/mohad/sources/gotk4-examples/gtk4/cssdemo/main.go:34 +0x6f fp=0xc00014fb88 sp=0xc00014fb00 pc=0x76190f
main.main.func1()
	/home/mohad/sources/gotk4-examples/gtk4/cssdemo/main.go:20 +0x1d fp=0xc00014fba0 sp=0xc00014fb88 pc=0x76187d
github.com/diamondburned/gotk4/pkg/gio/v2._gotk4_gio2_Application_ConnectActivate(0x54e4c6?, 0xc0000021a0?)
	/home/mohad/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20220221063304-bbd86ac49f1b/gio/v2/gapplication.go:589 +0x74 fp=0xc00014fbe8 sp=0xc00014fba0 pc=0x6165b4
_cgoexp_2e946dbfb880__gotk4_gio2_Application_ConnectActivate(0x7ffdfc9f4e60?)
	_cgo_gotypes.go:29184 +0x25 fp=0xc00014fc08 sp=0xc00014fbe8 pc=0x664c25
runtime.cgocallbackg1(0x664c00, 0xc00010fdc0?, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:314 +0x2ca fp=0xc00014fcd8 sp=0xc00014fc08 pc=0x54e3ca
runtime.cgocallbackg(0xc0000021a0?, 0x300000002?, 0xc0000021a0?)
	/usr/lib/go/src/runtime/cgocall.go:233 +0x109 fp=0xc00014fd68 sp=0xc00014fcd8 pc=0x54e049
runtime.cgocallbackg(0x664c00, 0x7ffdfc9f5200, 0x0)
	<autogenerated>:1 +0x2f fp=0xc00014fd90 sp=0xc00014fd68 pc=0x5ad0ef
runtime.cgocallback(0x54dec5, 0x7b8f80, 0xc00010fe20)
	/usr/lib/go/src/runtime/asm_amd64.s:971 +0xb4 fp=0xc00014fdb8 sp=0xc00014fd90 pc=0x5aabf4
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:436 fp=0xc00014fdc0 sp=0xc00014fdb8 pc=0x5a8c00
runtime.cgocall(0x7b8f80, 0xc00014fe20)
	/usr/lib/go/src/runtime/cgocall.go:167 +0x85 fp=0xc00014fdf8 sp=0xc00014fdc0 pc=0x54dec5
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x2709290, 0x1, 0x27492a0)
	_cgo_gotypes.go:5567 +0x4c fp=0xc00014fe20 sp=0xc00014fdf8 pc=0x60170c
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0xc00012f9b0?, 0x24?, 0x27492a0?)
	/home/mohad/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20220221063304-bbd86ac49f1b/gio/v2/gapplication.go:1616 +0x71 fp=0xc00014fe68 sp=0xc00014fe20 pc=0x617b11
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc00000e048, {0xc000012220?, 0x1, 0x1})
	/home/mohad/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20220221063304-bbd86ac49f1b/gio/v2/gapplication.go:1616 +0x1c5 fp=0xc00014ff28 sp=0xc00014fe68 pc=0x617a05
main.main()
	/home/mohad/sources/gotk4-examples/gtk4/cssdemo/main.go:22 +0xb4 fp=0xc00014ff80 sp=0xc00014ff28 pc=0x761834
runtime.main()
	/usr/lib/go/src/runtime/proc.go:250 +0x212 fp=0xc00014ffe0 sp=0xc00014ff80 pc=0x57fdf2
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00014ffe8 sp=0xc00014ffe0 pc=0x5aae21
exit status 2
```

**Comment by diamondburned** [comment]
Latest commit bumped `go4.org/unsafe/assume-no-moving-gc` to work with Go 1.18 now. The `cssdemo` crash turns out to be completely irrelevant and seems to have to do with how GTK handles CSS errors. Either way, that's also fixed.

**Comment by mohad12211** [comment]
I'm new to go so I didn't know they were irrelevant and I'm still trying to wrap my head around go modules, Thank you!
